function lc() { var a = H.document.createElement('iframe'); a.id = 'omid_v1_present'; a.name = 'omid_v1_present'; a.style.display = 'none'; H.document.body.appendChild(a) } function mc() { var a = new MutationObserver(function (b) { b.forEach(function (c) { 'BODY' === c.addedNodes[0].nodeName && (lc(), a.disconnect()) }) }); a.observe(H.document.documentElement, { childList: !0 }) }; var X = new Ta, hc = new function () { var a; this.a = a = void 0 === a ? omidGlobal : a }; new gc; var nc = new function () { }, oc = new function () { }, ec = new function () { this.b = X; this.c = oc; this.a = G() }, vc; H ? vc = H.IntersectionObserver && (H.MutationObserver || H.ResizeObserver) ? new O(H, nc, ec, X) : new N(H, oc, ec, hc, X) : vc = null; var Vb = vc, Wb = new function () { var a = X; var b = void 0 === b ? H : b; this.f = a; this.b = b; this.c = G(); this.a = [] }, bc = new Ub, fc = new function () { var a = X, b = G(); this.b = a; this.a = b }; H.omidBridge = new Z; new ac;
  if (H.frames && H.document && !('omid_v1_present' in H.frames)) { var wc; if (wc = null == H.document.body) wc = 'MutationObserver' in H; wc ? mc() : H.document.body ? lc() : H.document.write('<iframe style="display:none" id="omid_v1_present" name="omid_v1_present"></iframe>') };
}).call(this, this);

tart'); break; case 'SessionService.bufferFinish': Y(a.a,
            'bufferFinish'); break; case 'SessionService.skipped': Y(a.a, 'skipped'); break; case 'SessionService.volumeChange': c = { mediaPlayerVolume: p(d).next().value }; Y(a.a, 'volumeChange', c); break; case 'SessionService.playerStateChange': c = { state: p(d).next().value }; Y(a.a, 'playerStateChange', c); break; case 'SessionService.adUserInteraction': c = { interactionType: p(d).next().value }; Y(a.a, 'adUserInteraction', c); break; case 'SessionService.setClientInfo': var e = p(d); b = e.next().value; d = e.next().value; e = e.next().value; a = a.a.setClientInfo(b,
              d, e); c(a); break; case 'SessionService.injectVerificationScriptResources': c = p(d).next().value; a.a.injectVerificationScriptResources(c); break; case 'SessionService.setCreativeType': c = p(d).next().value; a.a.setCreativeType(c); break; case 'SessionService.setImpressionType': c = p(d).next().value; a.a.setImpressionType(c); break; case 'SessionService.setContentUrl': c = p(d).next().value; a.a.a.s = c; break; case 'SessionService.sessionError': b = p(d), c = b.next().value, b = b.next().value, a.a.error(c, b)
    }
  }; function Z() { var a = X, b = ec, c = fc, d = Vb; this.f = bc; this.a = a; this.c = b; this.h = c; this.g = d; this.b = G() } n = Z.prototype;
  n.S = function (a) {
    if (!(!(a && R(a) && T(a.impressionOwner, qa)) || 'videoEventsOwner' in a && null != a.videoEventsOwner && !T(a.videoEventsOwner, qa) || 'mediaEventsOwner' in a && null != a.mediaEventsOwner && !T(a.mediaEventsOwner, qa))) {
      if (a.creativeType && a.impressionType) { var b = a.mediaEventsOwner; null == this.b.a && this.f.setCreativeType(a.creativeType, b); null == this.b.f && (this.b.f = a.impressionType); nb(this.a, b) } else b = a.videoEventsOwner, this.b.b = null == b || 'none' === b ? 'display' : 'video', this.b.a = null, this.b.f = null, nb(this.a, b);
      ob(this.a, a.impressionOwner); a && null != a.isolateVerificationScripts && 'boolean' === typeof a.isolateVerificationScripts && (this.b.C = a.isolateVerificationScripts)
    }
  };
  n.V = function (a, b, c, d) {
    var e; if (R(b)) { if (e = T(b.environment, ta) && T(b.adSessionType, pa)) e = b.omidNativeInfo, e = R(e) ? S(e.partnerName) && S(e.partnerVersion) : !1; e && (e = b.app, e = R(e) ? S(e.libraryVersion) && S(e.appId) : !1) } else e = !1; e && (Mb(d) && (this.b.v = new Map(Object.entries(d))), d = this.f, c = void 0 === c ? null : c, null == a && (a = Sb()), d.a.adSessionId = a, a = d.a, e = a.c || {}, b.omidJsInfo = Object.assign({}, e.omidJsInfo || {}, b.omidJsInfo || {}), e = b = Object.assign({}, e, b), a.C || (null != a.i ? (e.videoElement = a.i, e.accessMode = 'full') : null !=
      a.h && (e.slotElement = a.h, e.accessMode = 'full')), a.c = b, void 0 !== b.contentUrl && (a.s = b.contentUrl), eb(d.c, c), d.b && M(d.b))
  }; n.T = function () { var a = this.f; ib(a.c); a.b.m() }; n.Z = function (a) { R(a) && Lb(a.x) && Lb(a.y) && Lb(a.width) && Lb(a.height) && (this.b.G = a, qb(this.c, 'container')) }; n.$ = function (a) { T(a, sa) && (this.b.m = a, 'backgrounded' === a ? qb(this.c, 'container', 'backgrounded') : qb(this.c, 'container')) }; n.W = function (a) { 'impression' === a && (this.L(), this.g && M(this.g)) }; n.L = function () { pb(this.a, 'native') && jb(this.a, 'native') };
  n.U = function (a) { a = void 0 === a ? null : a; K(this.a, 'native') && kb(this.a, 'native', a) }; n.error = function (a, b) { T(a, na) && db(this.a, a, b) }; n.X = function (a, b) { this.M(a, b) }; n.M = fun