function kc(a,b,c,d){if(null!=Tb(b))switch(Tb(b)){case 'registerAdEvents':a.a.registerAdEvents();break;case 'registerMediaEvents':a.a.registerMediaEvents();break;case 'registerSessionObserver':a.a.registerSessionObserver(c);break;case 'setSlotElement':c=p(d).next().value;a.a.setSlotElement(c);break;case 'setVideoElement':c=p(d).next().value;a=a.a;c&&c.tagName&&'video'===c.tagName.toLowerCase()?(a.a.g=c,a.b&&ub(a.b)):J('setVideoElement called with a non-HTMLVideoElement. It will be ignored.');break;
case 'setElementBounds':c=p(d).next().value;a.a.setElementBounds(c);break;case 'startSession':J('Session start from JS is not supported in mobile app.');break;case 'finishSession':J('Session finish from JS is not supported in mobile app.');break;case 'impressionOccurred':Y(a.a,'impression');break;case 'loaded':(c=p(d).next().value)?(b={skippable:c.isSkippable,autoPlay:c.isAutoPlay,position:c.position},c.isSkippable&&(b.skipOffset=c.skipOffset),Y(a.a,'loaded',b)):Y(a.a,'loaded');break;case 'start':b=
p(d);c=b.next().value;b=b.next().value;Y(a.a,'start',{duration:c,mediaPlayerVolume:b});break;case 'firstQuartile':Y(a.a,'firstQuartile');break;case 'midpoint':Y(a.a,'midpoint');break;case 'thirdQuartile':Y(a.a,'thirdQuartile');break;case 'complete':Y(a.a,'complete');break;case 'pause':Y(a.a,'pause');break;case 'resume':Y(a.a,'resume');break;case 'bufferStart':Y(a.a,'bufferStart');break;case 'bufferFinish':Y(a.a,'bufferFinish');break;case 'skipped':Y(a.a,'skipped');break;case 'volumeChange':c={mediaPlayerVolume:p(d).next().value};
Y(a.a,'volumeChange',c);break;case 'playerStateChange':c={state:p(d).next().value};Y(a.a,'playerStateChange',c);break;case 'adUserInteraction':c={interactionType:p(d).next().value};Y(a.a,'adUserInteraction',c);break;case 'setClientInfo':var e=p(d);b=e.next().value;d=e.next().value;e=e.next().value;a=a.a.setClientInfo(b,d,e);c(a);break;case 'injectVerificationScriptResources':c=p(d).next().value;a.a.injectVerificationScriptResources(c);break;case 'setCreativeType':c=p(d).next().value;a.a.setCreativeType(c);
break;case 'setImpressionType':c=p(d).next().value;a.a.setImpressionType(c);break;case 'setContentUrl':c=p(d).next().value;a.a.a.o=c;break;case 'sessionError':b=p(d),c=b.next().value,b=b.next().value,a.a.error(c,b)}};function Z(){var a=X,b=lc,c=mc,d=$b;this.f=hc;this.a=a;this.c=b;this.h=c;this.g=d;this.b=H()}n=Z.prototype;
n.T=function(a){if(!(!(a&&M(a)&&O(a.impressionOwner,qa))||'videoEventsOwner'in a&&null!=a.videoEventsOwner&&!O(a.videoEventsOwner,qa)||'mediaEventsOwner'in a&&null!=a.mediaEventsOwner&&!O(a.mediaEventsOwner,qa))){if(a.creativeType&&a.impressionType){var b=a.mediaEventsOwner;null==this.b.a&&this.f.setCreativeType(a.creativeType,b);null==this.b.h&&(this.b.h=a.impressionType);ob(this.a,b)}else b=a.videoEventsOwner,this.b.b=null==b||'none'===b?'display':'video',this.b.a=null,this.b.h=null,ob(this.a,b);
pb(this.a,a.impressionOwner);a&&null!=a.isolateVerificationScripts&&'boolean'===typeof a.isolateVerificationScripts&&(this.b.C=a.isolateVerificationScripts)}};
n.W=function(a,b,c,d){var e;if(M(b)){if(e=O(b.environment,ua)&&O(b.adSessionType,pa))e=b.omidNativeInfo,e=M(e)?N(e.partnerName)&&N(e.partnerVersion):!1;e&&(e=b.app,e=M(e)?N(e.libraryVersion)&&N(e.appId):!1)}else e=!1;e&&(Nb(d)&&(this.b.v=new Map(Object.entries(d))),d=this.f,c=void 0===c?null:c,null==a&&(a=Wb()),b.canMeasureVisibility=d.b.C(),d.a.adSessionId=a,a=d.a,e=b,void 0!==e.contentUrl&&(a.o=e.contentUrl,e.contentUrl=void 0),e=a.c||{},b.omidJsInfo=Object.assign({},e.omidJsInfo||{},b.omidJsInfo||
{}),e=b=Object.assign({},e,b),a.C||(null!=a.g?(e.videoElement=a.g,e.accessMode='full'):null!=a.f&&(e.slotElement=a.f,e.accessMode='full')),a.c=b,fb(d.c,c),d.b&&Q(d.b))};n.U=function(){var a=this.f;jb(a.c);a.b.m()};n.$=function(a){M(a)&&sb(a.x)&&sb(a.y)&&sb(a.width)&&sb(a.height)&&(this.b.G=a,rb(this.c,'container'))};n.aa=function(a){O(a,ta)&&(this.b.m=a,'backgrounded'===a?rb(this.c,'container','backgrounded'):rb(this.c,'container'))};n.X=function(a){'impression'===a&&(this.M(),this.g&&Q(this.g))};
n.M=function(){qb(this.a,'native')&&kb(this.a,'native')};n.V=function(a){a=void 0===a?null:a;L(this.a,'native')&&lb(this.a,'native',a)};n.error=function(a,b){O(a,oa)&&eb(this.a,a,b)};n.Y=function(a,b){this.N(a,b)};n.N=function(a,b){L(this.a,'native')&&O(a,A)&&(void 0===b||M(b))&&('loaded'==a?lb(this.a,'native',b):mb(this.a,a,'native',b))};
n.Z=function(a){if('none'!==this.a.a.i&&'number'===typeof a&&!isNaN(a)){this.b.u=a;a=this.h;var b=a.a.B;null!=b&&mb(a.b,'volumeChange','native',{mediaPlayerVolume:b,deviceVolume:a.a.u})}};Z.prototype.startSession=Z.prototype.W;Z.prototype.error=Z.prototype.error;Z.prototype.finishSession=Z.prototype.U;Z.prototype.publishAdEvent=Z.prototype.X;Z.prototype.publishImpressionEvent=Z.prototype.M;Z.prototype.publishVideoEvent=Z.prototype.Y;Z.prototype.publishMediaEvent=Z.prototype.N;
Z.prototype.publishLoadedEvent=Z.prototype.V;Z.prototype.setNativeViewHierarchy=Z.prototype.$;Z.prototype.setState=Z.prototype.aa;Z.prototype.setDeviceVolume=Z.prototype.Z;Z.prototype.init=Z.prototype.T;function nc(){var a=X,b=oc;var c=void 0===c?I:c;this.g=a;this.a=b;this.h={};this.f={};this.c=new U;c.omid=c.omid||{};c.omid.v1_VerificationServiceCommunication=this.c;this.b=null;c&&c.addEventListener&&c.postMessage&&(this.b=new Vb(c));this.c.a=this.i.bind(this);this.b&&(this.b.a=this.j.bind(this))}function pc(a,b,c,d){Db(a.a,b,c,d)}function qc(a,b,c,d){Cb(a.a,'downloadJavaScriptResource')(b,c,d)}nc.prototype.j=function(a,b){this.b&&rc(this,a,b,this.b)};nc.prototype.i=function(a,b){rc(this,a,b,this.c)};
function rc(a,b,c,d){function e(F){for(var W=[],ra=0;ra<arguments.length;++ra)W[ra]=arguments[ra];W=new T(f,'response',g,cc(g)&&dc(g)?W:JSON.stringify(W));d.b(W,c)}var f=b.b,l=b.method,g=b.version;b=ec(g,b.a);if(null!=Ub(l,'VerificationService.')){l=Ub(l,'VerificationService.');try{switch(l){case 'addEventListener':var h=p(b).next().value;$a(a.g,h,e);break;case 'addSessionListener':var k=p(b),m=k.next().value,u=k.next().value;bb(a.g,e,m,u);break;case 'sendUrl':var w=p(b).next().value;pc(a,w,function(){return e(!0)},
function(){return e(!1)});break;case 'setTimeout':var E=p(b),V=E.next().value,wc=E.next().value;a.h[V]=zb(a.a,'setTimeout')(e,wc);break;case 'clearTimeout':var xc=p(b).next().value;Bb(a.a,a.h[xc]);break;case 'setInterval':var Ob=p(b),yc=Ob.next().value,zc=Ob.next().value;a.f[yc]=yb(a.a,e,zc);break;case 'clearInterval':var Ac=p(b).next().value;Ab(a.a,a.f[Ac]);break;case 'injectJavaScriptResource':var Bc=p(b).next().value;qc(a,Bc,function(F){return e(!0,F)},function(){return e(!1)});break;case 'getVersion':p(b).next();
var Cc=H().c.omidJsInfo;e(Cc.serviceVersion)}}catch(F){d.b(new T(f,'error',g,'\n              name: '+F.name+'\n              message: '+F.message+'\n              filename: '+F.filename+'\n              lineNumber: '+F.lineNumber+'\n              columnNumber: '+F.columnNumber+'\n              stack: '+F.stack+'\n              toString(): '+F.toString()+'\n          '),c)}}};function sc(){var a=I.document.createElement('iframe');a.id='omid_v1_present';a.name='omid_v1_present';a.style.display='none';I.document.body.appendChild(a)}function tc(){var a=new MutationObserver(function(b){b.forEach(function(c){'BODY'===c.addedNodes[0].nodeName&&(sc(),a.disconnect())})});a.observe(I.document.documentElement,{childList:!0})};var X=new Ua,oc=new function(){var a;this.a=a=void 0===a?omidGlobal:a};new nc;var uc=new function(){},vc=new function(){},lc=new function(){this.b=X;this.c=vc;this.a=H()},Dc;I?Dc=I.IntersectionObserver&&(I.MutationObserver||I.ResizeObserver)?new S(I,uc,lc,X):new R(I,vc,lc,oc,X):Dc=null;var $b=Dc,ac=new function(){var a=X;var b=void 0===b?I:b;this.f=a;this.a=b;this.c=H();this.b=[]},hc=new Zb,mc=new function(){var a=X,b=H();this.b=a;this.a=b};I.omidBridge=new Z;new gc;
if(I.frames&&I.document&&!('omid_v1_present'in I.frames)){var Ec;if(Ec=null==I.document.body)Ec='MutationObserver'in I;Ec?tc():I.document.body?sc():I.document.write('<iframe style="display:none" id="omid_v1_present" name="omid_v1_present"></iframe>')};
}).call(this, this);