function (a, b) { this.M(a, b) }; n.M = function (a, b) { K(this.a, 'native') && T(a, y) && (void 0 === b || R(b)) && ('loaded' == a ? kb(this.a, 'native', b) : lb(this.a, a, 'native', b)) }; n.Y = function (a) { if ('none' !== this.a.a.g && 'number' === typeof a && !isNaN(a)) { this.b.u = a; a = this.h; var b = a.a.B; null != b && lb(a.b, 'volumeChange', 'native', { mediaPlayerVolume: b, deviceVolume: a.a.u }) } }; Z.prototype.startSession = Z.prototype.V;
  Z.prototype.error = Z.prototype.error; Z.prototype.finishSession = Z.prototype.T; Z.prototype.publishAdEvent = Z.prototype.W; Z.prototype.publishImpressionEvent = Z.prototype.L; Z.prototype.publishVideoEvent = Z.prototype.X; Z.prototype.publishMediaEvent = Z.prototype.M; Z.prototype.publishLoadedEvent = Z.prototype.U; Z.prototype.setNativeViewHierarchy = Z.prototype.Z; Z.prototype.setState = Z.prototype.$; Z.prototype.setDeviceVolume = Z.prototype.Y; Z.prototype.init = Z.prototype.S; function gc() { var a = X, b = hc; var c = void 0 === c ? H : c; this.g = a; this.a = b; this.h = {}; this.f = {}; this.c = new V; c.omid = c.omid || {}; c.omid.v1_VerificationServiceCommunication = this.c; this.b = null; c && c.addEventListener && c.postMessage && (this.b = new Rb(c)); this.c.a = this.i.bind(this); this.b && (this.b.a = this.j.bind(this)) } function ic(a, b, c, d) { Ab(a.a, b, c, d) } function jc(a, b, c, d) { zb(a.a, 'downloadJavaScriptResource')(b, c, d) } gc.prototype.j = function (a, b) { this.b && kc(this, a, b, this.b) }; gc.prototype.i = function (a, b) { kc(this, a, b, this.c) };
  function kc(a, b, c, d) {
    function e(B) { for (var W = [], oa = 0; oa < arguments.length; ++oa)W[oa] = arguments[oa]; W = new U(g, 'response', f, Yb(f) && Zb(f) ? W : JSON.stringify(W)); d.b(W, c) } var g = b.b, l = b.method, f = b.version; b = $b(f, b.a); try {
      switch (l) {
        case 'VerificationService.addEventListener': var h = p(b).next().value; Za(a.g, h, e); break; case 'VerificationService.addSessionListener': var k = p(b), m = k.next().value, z = k.next().value; ab(a.g, e, m, z); break; case 'VerificationService.sendUrl': var xa = p(b).next().value; ic(a, xa, function () { return e(!0) },
          function () { return e(!1) }); break; case 'VerificationService.setTimeout': var P = p(b), Q = P.next().value, F = P.next().value; a.h[Q] = wb(a.a, 'setTimeout')(e, F); break; case 'VerificationService.clearTimeout': var pc = p(b).next().value; yb(a.a, a.h[pc]); break; case 'VerificationService.setInterval': var Jb = p(b), qc = Jb.next().value, rc = Jb.next().value; a.f[qc] = vb(a.a, e, rc); break; case 'VerificationService.clearInterval': var sc = p(b).next().value; xb(a.a, a.f[sc]); break; case 'VerificationService.injectJavaScriptResource': var tc =
            p(b).next().value; jc(a, tc, function (B) { return e(!0, B) }, function () { return e(!1) }); break; case 'VerificationService.getVersion': p(b).next(); var uc = G().c.omidJsInfo; e(uc.serviceVersion)
      }
    } catch (B) {
      d.b(new U(g, 'error', f, '\n              name: ' + B.name + '\n              message: ' + B.message + '\n              filename: ' + B.filename + '\n              lineNumber: ' + B.lineNumber + '\n              columnNumber: ' + B.columnNumber + '\n              stack: ' + B.stack + '\n              toString(): ' + B.toString() + '\n          '),
        c)
    }
  }; function lc() { var a = H.document.createElement('iframe'); a.id = 'omid_v1_present'; a.name = 'omid_v1_present'; a.style.display = 'none'; H.document.body.appendChild(a) } function mc() { var a = new MutationObserver(function (b) { b.forEach(function (c) { 'BODY' === c.addedNodes[0].nodeName && (lc(), a.disconnect()) }) }); a.observe(H.document.documentElement, { childList: !0 }) }; var X = new Ta, hc = new function () { var a; this.a = a = void 0 === a ? omidGlobal : a }; new gc; var nc = new function () { }, oc = new function () { }, ec = new function () { this.b = X; this.c = oc; this.a = G() }, vc; H ? vc = H.IntersectionObserver && (H.MutationObserver || H.ResizeObserver) ? new O(H, nc, ec, X) : new N(H, oc, ec, hc, X) : vc = null; var Vb = vc, Wb = new function () { var a = X; var b = void 0 === b ? H : b; this.f = a; this.b = b; this.c = G(); this.a = [] }, bc = new Ub, fc = new function () { var a = X, b = G(); this.b = a; this.a = b }; H.omidBridge = new Z; new ac;
  if (H.frames && H.document && !('omid_v1_present' in H.frames)) { var wc; if (wc = null == H.document.body) wc = 'MutationObserver' in H; wc ? mc() : H.document.body ? lc() : H.document.write('<iframe style="display:none" id="omid_v1_present" name="omid_v1_present"></iframe>') };
}).call(this, this);

