function(){this.urlScheme="";this.executeNativeCall=function(a){if(imIsObjValid(__im__iosNativeMessageHandler)){f={};f.command=a;f.scheme=this.urlScheme;for(var b={},c=1;c<arguments.length;c+=2)d=arguments[c+1],null!=d&&(b[arguments[c]]=""+d);f.params=b}else for(var f=this.urlScheme+"://"+a,d,b=!0,c=1;c<arguments.length;c+=2)d=arguments[c+1],null!=d&&(b?(f+="?",b=!1):f+="&",f+=arguments[c]+"="+escape(d));__im__iosNativeCall.executeNativeCall(f);return"OK"};this.nativeCallComplete=
function(a){__im__iosNativeCall.nativeCallComplete(a);return"OK"};this.updateKV=function(a,b){this[a]=b;var c=this.broadcastMap[a];c&&this.broadcastEvent(c,b)}};
(function(){var a=window.mraidview={};a.orientationProperties={allowOrientationChange:!0,forceOrientation:"none",direction:"right"};var b=[],c=!1;a.detectAndBlockFraud=function(f){a.isPossibleFraud()&&a.fireRedirectFraudBeacon(f);return!1};a.popupBlocked=function(f){a.firePopupBlockedBeacon(f)};a.zeroPad=function(a){var c="";10>a&&(c+="0");return c+a};a.supports=function(a){console.log("bridge: supports (MRAID)");if("string"!=typeof a)window.mraid.broadcastEvent("error","Supports method expects string parameter",
"supports");else return"false"!=sdkController.supports("window.mraidview",a)};a.useCustomClose=function(a){try{sdkController.useCustomClose("window.mraidview",a)}catch(c){imraidview.showAlert("use CustomClose: "+c)}};a.close=function(){try{sdkController.close("window.mraidview")}catch(a){imraidview.showAlert("close: "+a)}};a.stackCommands=function(a,d){c?b.push(a):(eval(a),d&&(c=!0))};a.setOrientationProperties=function(f){try{f?("undefined"!=typeof f.allowOrientationChange&&(a.orientationProperties.allowOrientationChange=
f.allowOrientationChange),"undefined"!=typeof f.forceOrientation&&(a.orientationProperties.forceOrientation=f.forceOrientation)):f=null,sdkController.setOrientationProperties("window.mraidview",a.stringify(a.orientationProperties))}catch(c){imraidview.showAlert("setOrientationProperties: "+c+", props = "+f)}};a.getOrientationProperties=function(){return{forceOrientation:a.orientationProperties.forceOrientation,allowOrientationChange:a.orientationProperties.allowOrientationChange}};a.resizeProps=null;
a.open=function(a){"undefined"==typeof a&&(a=null);try{sdkController.open("window.mraidview",a)}catch(c){imraidview.showAlert("open: "+c)}};a.getScreenSize=function(){try{return eval("("+sdkController.getScreenSize("window.mraidview")+")")}catch(a){imraidview.showAlert("getScreenSize: "+a)}};a.getMaxSize=function(){try{return eval("("+sdkController.getMaxSize("window.mraidview")+")")}catch(a){imraidview.showAlert("getMaxSize: "+a)}};a.getCurrentPosition=function(){try{return eval("("+sdkController.getCurrentPosition("window.mraidview")+
")")}catch(a){imraidview.showAlert("getCurrentPosition: "+a)}};a.getDefaultPosition=function(){try{return eval("("+sdkController.getDefaultPosition("window.mraidview")+")")}catch(a){imraidview.showAlert("getDefaultPosition: "+a)}};a.getState=function(){try{return String(sdkController.getState("window.mraidview"))}catch(a){imraidview.showAlert("getState: "+a)}};a.isViewable=function(){if(imraidview.fallbackViewabilityEnabled())return imraidview.checkFallbackViewable();try{return sdkController.isViewable("window.mraidview")}catch(a){imraidview.showAlert("isViewable: "+
a)}};a.getPlacementType=function(){return sdkController.getPlacementType("window.mraidview")};a.close=function(){try{sdkController.close("window.mraidview")}catch(a){imraidview.showAlert("close: "+a)}};"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});a.playVideo=function(a){var c="";null!=a&&(c=a);try{sdkController.playVideo("window.mraidview",c)}catch(b){imraidview.showAlert("playVideo: "+b)}};a.stringify=function(c){if("undefined"===
typeof JSON){var b="",e;if("undefined"==typeof c.length)return a.stringifyArg(c);for(e=0;e<c.length;e++)0<e&&(b+=","),b+=a.stringifyArg(c[e]);return b+"]"}return JSON.stringify(c)};a.stringifyArg=function(a){var c,b,g;b=typeof a;c="";if("number"===b||"boolean"===b)c+=args;else if(a instanceof Array)c=c+"["+a+"]";else if(a instanceof Object){b=!0;c+="{";for(g in a)null!==a[g]&&(b||(c+=","),c=c+'"'+g+'":',b=typeof a[g],c="number"===b||"boolean"===b?c+a[g]:"function"===typeof a[g]?c+'""':a[g]instanceof
Object?c+this.stringify(args[i][g]):c+'"'+a[g]+'"',b=!1);c+="}"}else a=a.replace(/\\/g,"\\\\"),a=a.replace(/"/g,'\\"'),c=c+'"'+a+'"';imraidview.showAlert("json:"+c);return c};getPID=function(a){var c="";null!=a&&("undefined"!=typeof a.id&&null!=a.id)&&(c=a.id);return c};a.storePicture=function(c){console.log("bridge: storePicture");if("string"!=typeof c)window.mraid.broadcastEvent("error","storePicture method expects url as string parameter","storePicture");else{if(a.supports("storePicture"))return!window.confirm("Do you want to download the file?")?
(window.mraid.broadcastEvent("error","Store picture on "+c+" was cancelled by user.","storePicture"),!1):sdkController.storePicture("window.mraidview",c);window.mraid.broadcastEvent("error","Store picture on "+c+" was cancelled because it is unsupported in this device/app.","storePicture")}};a.fireMediaTrackingEvent=function(a,c){};a.fireMediaErrorEvent=function(a,c){};a.fireMediaTimeUpdateEvent=function(a,c,b){};a.fireMediaCloseEvent=function(a,c,b){};a.fireMediaVolumeChangeEvent=function(a,c,b){};
a.broadcastEvent=function(){window.mraid.broadcastEvent.apply(window.mraid,arguments)};a.unload=function(){try{sdkController.unload("window.mraidview")}catch(a){}};a.getCurrentAppOrientation=function(){var c;switch(a.orientation){case 0:case 180:c="portrait";break;case 90:case 270:c="landscape";break;default:c="none"}return{orientation:c,locked:!1}};a.expand=function(a){try{"undefined"==typeof a&&(a=null),sdkController.expand("window.mraidview",a)}catch(c){imraidview.showAlert("executeNativeExpand: "+
c+", URL = "+a)}};a.setExpandProperties=function(c){try{c?this.props=c:c=null;if("undefined"!=typeof c.lockOrientation&&null!=c.lockOrientation&&"undefined"!=typeof c.orientation&&null!=c.orientation){var b={};b.allowOrientationChange=!c.lockOrientation;b.forceOrientation=c.orientation;a.setOrientationProperties(b)}sdkController.setExpandProperties("window.mraidview",a.stringify(c))}catch(e){imraidview.showAlert("executeNativesetExpandProperties: "+e+", props = "+c)}};a.getExpandProperties=function(){try{return eval("("+
sdkController.getExpandProperties("window.mraidview")+")")}catch(a){imraidview.showAlert("getExpandProperties: "+a)}};a.resizeProps=null;a.setResizeProperties=function(c){var b,e;try{b=parseInt(c.width);e=parseInt(c.height);if(isNaN(b)||isNaN(e)||1>b||1>e)throw"Invalid";c.width=b;c.height=e;a.resizeProps=c;sdkController.setResizeProperties("window.mraidview",a.stringify(c))}catch(g){window.mraid.broadcastEvent("error","Invalid properties.","setResizeProperties")}};a.getResizeProperties=function(){try{return eval("("+
sdkController.getResizeProperties("window.mraidview")+")")}catch(a){imraidview.showAlert("getResizeProperties: "+a)}};a.resize=function(){if(null==a.resizeProps)window.mraid.broadcastEvent("error","Valid resize dimensions must be provided before calling resize","resize");else try{sdkController.resize("window.mraidview")}catch(c){imraidview.showAlert("resize called in bridge")}}})();
(function(){var a=window.mraid=new InmobiObj,b=window.mraidview,c=!1;b.isAdShownToUser=!1;b.onUserInteraction=function(){imraidview.onUserInteraction();c=!0};b.isPossibleFraud=function(){return a.supports("redirectFraudDetection")&&(!b.isAdShownToUser||!c)};b.fireRedirectFraudBeacon=function(a){if("undefined"!=typeof inmobi&&inmobi.recordEvent){var c={};c.trigger=a;c.isAdShown=b.isAdShownToUser.toString();inmobi.recordEvent(135,c)}};b.getSdkVersionInt=function(){for(var a=imraid.getSdkVersion().split("."),
c=a.length,b="",g=0;g<c;g++)b+=a[g];return parseInt(b)};b.firePopupBlockedBeacon=function(a){if("undefined"!=typeof inmobi&&inmobi.recordEvent){var c={};c.trigger=a;inmobi.recordEvent(136,c)}};window.onbeforeunload=function(){b.detectAndBlockFraud("redirect")};a.addEventListener("viewableChange",function(a){a&&!b.isAdShownToUser&&(b.isAdShownToUser=!0)});a.useCustomClose=b.useCustomClose;a.close=b.close;a.getExpandProperties=function(){if(1083<=b.getSdkVersionInt())return window.mraid.broadcastEvent("error",
"Method not supported","getExpandProperties"),null;window.mraid.broadcastEvent("error","MRAID getExpandProperties is deprecated","getExpandProperties");return b.getExpandProperties()};a.setExpandProperties=function(c){1083<=b.getSdkVersionInt()?window.mraid.broadcastEvent("error","Method not supported","setExpandProperties"):("undefined"!=typeof c&&("useCustomClose"in c&&"undefined"!=typeof a.getState()&&"expanded"!=a.getState())&&a.useCustomClose(c.useCustomClose),window.mraid.broadcastEvent("error",
"MRAID setExpandProperties is deprecated","setExpandProperties"),b.setExpandProperties(c))};a.getResizeProperties=function(){if(1083<=b.getSdkVersionInt())return window.mraid.broadcastEvent("error","Method not supported","getResizeProperties"),null;window.mraid.broadcastEvent("error","MRAID getResizeProperties is deprecated","getResizeProperties");return b.getResizeProperties()};a.setResizeProperties=function(a){1083<=b.getSdkVersionInt()?window.mraid.broadcastEvent("error","Method not supported",
"setResizeProperties"):(window.mraid.broadcastEvent("error","MRAID setResizeProperties is deprecated","setResizeProperties"),b.setResizeProperties(a))};a.getOrientationProperties=b.getOrientationProperties;a.setOrientationProperties=b.setOrientationProperties;a.expand=function(a){try{1083<=b.getSdkVersionInt()?window.mraid.broadcastEvent("error","Method not supported","expand"):(window.mraid.broadcastEvent("error","MRAID expand is deprecated","expand"),b.expand(a))}catch(c){window.mraid.broadcastEvent("error",
"error","expand")}};a.getMaxSize=b.getMaxSize;a.getState=b.getState;a.isViewable=b.isViewable;a.createCalendarEvent=function(a){window.mraid.broadcastEvent("error","Method not supported","createCalendarEvent")};a.open=function(c){b.detectAndBlockFraud("mraid.open")||("string"!=typeof c?a.broadcastEvent("error","URL is required.","open"):b.open(c))};a.resize=function(){try{1083<=b.getSdkVersionInt()?window.mraid.broadcastEvent("error","MRAID resize not supported","resize"):(window.mraid.broadcastEvent("error",
"MRAID resize is deprecated","resize"),b.expand())}catch(a){window.mraid.broadcastEvent("error","error","expand")}};a.getVersion=function(){return"3.0"};a.getPlacementType=b.getPlacementType;a.playVideo=function(a){b.playVideo(a)};a.getScreenSize=b.getScreenSize;a.getCurrentPosition=b.getCurrentPosition;a.getDefaultPosition=b.getDefaultPosition;a.supports=function(a){return b.supports(a)};a.storePicture=function(c){"string"!=typeof c?a.broadcastEvent("error","Request must specify a valid URL","storePicture"):
b.storePicture(c)};a.unload=function(){b.unload()};a.getCurrentAppOrientation=b.getCurrentAppOrientation;a.getLocation=function(){return null};a.getAudioVolume=b.getAudioVolume})();
(function(){var a=window.imraidview={},b=!1;a.setOrientationProperties=function(c){try{c?("undefined"!=typeof c.allowOrientationChange&&(mraidview.orientationProperties.allowOrientationChange=c.allowOrientationChange),"undefined"!=typeof c.forceOrientation&&(mraidview.orientationProperties.forceOrientation=c.forceOrientation),"undefined"!=typeof c.direction&&(mraidview.orientationProperties.direction=c.direction)):c=null,sdkController.setOrientationProperties("window.imraidview",mraidview.stringify(mraidview.orientationProperties))}catch(b){a.showAlert("setOrientationProperties: "+
b+", props = "+c)}};a.getOrientationProperties=function(){return mraidview.orientationProperties};a.firePostStatusEvent=function(a){window.imraid.broadcastEvent("postStatus",a)};a.fireMediaTrackingEvent=function(a,b){var d={};d.name=a;var e="inmobi_media_"+a;"undefined"!=typeof b&&(null!=b&&""!=b)&&(e=e+"_"+b);window.imraid.broadcastEvent(e,d)};a.fireMediaErrorEvent=function(a,b){var d={name:"error"};d.code=b;var e="inmobi_media_"+d.name;"undefined"!=typeof a&&(null!=a&&""!=a)&&(e=e+"_"+a);window.imraid.broadcastEvent(e,
d)};a.fireMediaTimeUpdateEvent=function(a,b,d){var e={name:"timeupdate",target:{}};e.target.currentTime=b;e.target.duration=d;b="inmobi_media_"+e.name;"undefined"!=typeof a&&(null!=a&&""!=a)&&(b=b+"_"+a);window.imraid.broadcastEvent(b,e)};a.saveContent=function(a,b,d){window.imraid.addEventListener("saveContent_"+a,d);sdkController.saveContent("window.imraidview",a,b)};a.cancelSaveContent=function(a){sdkController.cancelSaveContent("window.imraidview",a)};a.disableCloseRegion=function(a){sdkController.disableCloseRegion("window.imraidview",
a)};a.fireGalleryImageSelectedEvent=function(a,b,d){var e=new Image;e.src="data:image/jpeg;base64,"+a;e.width=b;e.height=d;window.imraid.broadcastEvent("galleryImageSelected",e)};a.fireCameraPictureCatpturedEvent=function(a,b,d){var e=new Image;e.src="data:image/jpeg;base64,"+a;e.width=b;e.height=d;window.imraid.broadcastEvent("cameraPictureCaptured",e)};a.fireMediaCloseEvent=function(a,b,d){var e={name:"close"};e.viaUserInteraction=b;e.target={};e.target.currentTime=d;b="inmobi_media_"+e.name;"undefined"!=
typeof a&&(null!=a&&""!=a)&&(b=b+"_"+a);window.imraid.broadcastEvent(b,e)};a.fireMediaVolumeChangeEvent=function(a,b,d){var e={name:"volumechange",target:{}};e.target.volume=b;e.target.muted=d;b="inmobi_media_"+e.name;"undefined"!=typeof a&&(null!=a&&""!=a)&&(b=b+"_"+a);window.imraid.broadcastEvent(b,e)};a.fireDeviceMuteChangeEvent=function(a){window.imraid.broadcastEvent("deviceMuted",a)};a.fireDeviceVolumeChangeEvent=function(a){window.imraid.broadcastEvent("deviceVolumeChange",a)};a.fireHeadphonePluggedEvent=
function(a){window.imraid.broadcastEvent("headphones",a)};a.showAlert=function(a){sdkController.showAlert("window.imraidview",a)};a.openExternal=function(c,b){try{600<=getSdkVersionInt()?sdkController.openExternal("window.imraidview",c,b):sdkController.openExternal("window.imraidview",c)}catch(d){a.showAlert("openExternal: "+d)}};a.log=function(c){try{sdkController.log("window.imraidview",c)}catch(b){a.showAlert("log: "+b)}};a.getPlatform=function(){return"android"};a.asyncPing=function(c){try{sdkController.asyncPing("window.imraidview",
c)}catch(b){a.showAlert("asyncPing: "+b)}};a.startListeningDeviceMuteEvents=function(){sdkController.registerDeviceMuteEventListener("window.imraidview")};a.stopListeningDeviceMuteEvents=function(){sdkController.unregisterDeviceMuteEventListener("window.imraidview")};a.startListeningDeviceVolumeChange=function(){sdkController.registerDeviceVolumeChangeEventListener("window.imraidview")};a.stopListeningDeviceVolumeChange=function(){sdkController.unregisterDeviceVolumeChangeEventListener("window.imraidview")};
a.startListeningHeadphonePluggedEvents=function(){sdkController.registerHeadphonePluggedEventListener("window.imraidview")};a.stopListeningHeadphonePluggedEvents=function(){sdkController.unregisterHeadphonePluggedEventListener("window.imraidview")};getSdkVersionInt=function(){for(var c=a.getSdkVersion().split("."),b=c.length,d="",e=0;e<b;e++)d+=c[e];return parseInt(d)};a.getSdkVersionInt=getSdkVersionInt;a.getSdkVersion=function(){return window._im_imaiview.getSdkVersion()};a.supports=function(a){console.log("bridge: supports (IMRAID)");
if("string"!=typeof a)window.imraid.broadcastEvent("error","Supports method expects string parameter","supports");else return"false"!=sdkController.supports("window.imraidview",a)};a.postToSocial=function(c,b,d,e){window.imraid.broadcastEvent("error","Method not supported","postToSocial");a.log("Method postToSocial not supported")};a.incentCompleted=function(a){if("object"!=typeof a||null==a)sdkController.incentCompleted("window.imraidview",null);else try{sdkController.incentCompleted("window.imraidview",
JSON.stringify(a))}catch(b){sdkController.incentCompleted("window.imraidview",null)}};a.getOrientation=function(){try{return String(sdkController.getOrientation("window.imraidview"))}catch(c){a.showAlert("getOrientation: "+c)}};a.acceptAction=function(c){try{sdkController.acceptAction("window.imraidview",mraidview.stringify(c))}catch(b){a.showAlert("acceptAction: "+b+", params = "+c)}};a.rejectAction=function(c){try{sdkController.rejectAction("window.imraidview",mraidview.stringify(c))}catch(b){a.showAlert("rejectAction: "+
b+", params = "+c)}};a.updateToPassbook=function(c){window.imraid.broadcastEvent("error","Method not supported","updateToPassbook");a.log("Method not supported")};a.isDeviceMuted=function(){return"false"!=sdkController.isDeviceMuted("window.imraidview")};a.getDeviceVolume=function(){return 603>=getSdkVersionInt()?-1:sdkController.getDeviceVolume("window.imraidview")};a.isHeadPhonesPlugged=function(){return"false"!=sdkController.isHeadphonePlugged("window.imraidview")};a.sendSaveContentResult=function(){window.imraid.sendSaveContentResult.apply(window.imraid,
arguments)};a.broadcastEvent=function(){window.imraid.broadcastEvent.apply(window.imraid,arguments)};a.disableBackButton=function(a){void 0==a||"boolean"!=typeof a?console.log("disableBackButton called with invalid params"):sdkController.disableBackButton("window.imraidview",a)};a.isBackButtonDisabled=function(){return sdkController.isBackButtonDisabled("window.imraidview")};a.startListeningForBackButtonPressedEvent=function(){sdkController.registerBackButtonPressedEventListener("window.imraidview")};
a.stopListeningForBackButtonPressedEvent=function(){sdkController.unregisterBackButtonPressedEventListener("window.imraidview")};a.hideStatusBar=function(){};a.setOpaqueBackground=function(){};a.startDownloader=function(a,b,d){682<=getSdkVersionInt()&&sdkController.startDownloader("window.imraidview",a,b,d)};a.registerDownloaderCallbacks=function(){682<=getSdkVersionInt()&&sdkController.registerDownloaderCallbacks("window.imraidview")};a.unregisterDownloaderCallbacks=function(){682<=getSdkVersionInt()&&
sdkController.unregisterDownloaderCallbacks("window.imraidview")};a.getDownloadProgress=function(){return 682<=getSdkVersionInt()?sdkController.getDownloadProgress("window.imraidview"):-1};a.getDownloadStatus=function(){return 682<=getSdkVersionInt()?sdkController.getDownloadStatus("window.imraidview"):-1};a.fireEvent=function(a){700<=getSdkVersionInt()&&("fireSkip"===a?sdkController.fireSkip("window.imraidview"):"fireComplete"===a?sdkController.fireComplete("window.imraidview"):"showEndCard"===a&&
sdkController.showEndCard("window.imraidview"))};a.saveBlob=function(a){700<=getSdkVersionInt()&&sdkController.saveBlob("window.imraidview",a)};a.getBlob=function(a,b){700<=getSdkVersionInt()&&sdkController.getBlob(a,b)};a.setCloseEndCardTracker=function(a){700<=getSdkVersionInt()&&sdkController.setCloseEndCardTracker("window.imraidview",a)};a.getRenderableAdIndexes=function(){try{if(917<=getSdkVersionInt())return sdkController.getRenderableAdIndexes("window.imraidview")}catch(a){}return"[]"};a.getCurrentRenderingIndex=
function(){try{if(917<=getSdkVersionInt())return sdkController.getCurrentRenderingIndex("window.imraidview")}catch(a){}return-1};a.showAd=function(a){try{917<=getSdkVersionInt()&&sdkController.showAd("window.imraidview",a)}catch(b){}};a.timeSinceShow=function(){try{if(917<=getSdkVersionInt())return sdkController.timeSinceShow("window.imraidview")}catch(a){}return-1};a.getShowTimeStamp=function(){try{if(917<=getSdkVersionInt())return sdkController.getShowTimeStamp("window.imraidview")}catch(a){}return-1};
a.closeAll=function(){try{917<=getSdkVersionInt()&&sdkController.closeAll("window.imraidview")}catch(a){}};a.loadAd=function(a){try{917<=getSdkVersionInt()&&sdkController.loadAd("window.imraidview",a)}catch(b){}};a.setAdContext=function(a){try{917<=getSdkVersionInt()&&sdkController.setAdContext("window.imraidview",a)}catch(b){}};a.getAdContext=function(){try{if(917<=getSdkVersionInt())return sdkController.getAdContext("window.imraidview")}catch(a){}return""};a.openWithoutTracker=function(a){try{"undefined"==
typeof a&&(a=null),sdkController.openWithoutTracker("window.imraidview",a)}catch(b){}};a.impressionRendered=function(){window.imraid.broadcastEvent("impressionRendered")};a.customExpandInNative=function(a,b,d){try{void 0==a||"string"!=typeof a?console.log("url called with invalid params"):void 0==b||"number"!=typeof b?console.log("screenPercentage called with invalid params"):void 0==d||"boolean"!=typeof d?console.log("hideCloseButton called with invalid params"):sdkController.customExpandInNative("window.imraidview",
a,b,d)}catch(e){}};a.customExpand=function(b,f,d,e,g){try{void 0==d||"number"!=typeof d?console.log("screenPercentage called with invalid params"):void 0==f||"number"!=typeof f?console.log("inputType called with invalid params"):void 0==e||"boolean"!=typeof e?console.log("topNavBarVisible called with invalid params"):void 0==g||"boolean"!=typeof g?console.log("bottomNavBarVisible called with invalid params"):sdkController.customExpand("window.imraidview",b,f,d,e,g)}catch(h){a.showAlert("executeNativeCustomExpand: "+
h+", input = "+b+", inputType = "+f+", screenPercentage = "+d+", bottomNavBarVisible = "+g+", topNavBarVisible = "+e)}};a.closeCustomExpand=function(){try{sdkController.closeCustomExpand("window.imraidview")}catch(a){}};a.onGestureDetected=function(a,b){window.imraid.broadcastEvent("onGestureDetected",a,b)};a.onUserLandingCompleted=function(){window.imraid.broadcastEvent("onUserLandingCompleted")};a.onUserInteraction=function(){window.imraid.broadcastEvent("onUserInteraction")};a.impressionFired=
function(){try{sdkController.impressionFired("window.imraidview")}catch(a){}};a.getMaxDeviceVolume=function(){try{return sdkController.getMaxDeviceVolume("window.imraidview")}catch(a){return 15}};a.zoom=function(a){try{sdkController.zoom("window.imraidview",a)}catch(b){}};a.onAudioStateChanged=function(a){try{sdkController.onAudioStateChanged("window.imraidview",a)}catch(b){}};a.submitAdReport=function(a){try{sdkController.submitAdReport("window.imraidview",void 0!=a.adQualityUrl?a.adQualityUrl:null,
void 0!=a.enableUserAdReportScreenshot?a.enableUserAdReportScreenshot:null,void 0!=a.templateInfo?a.templateInfo:null)}catch(b){}};a.logTelemetryEvent=function(a){try{var b=void 0!=a.eventType?a.eventType:null,d=void 0!=a.payload?a.payload:null;a=null;null!=d&&(a=mraidview.stringify(d));sdkController.logTelemetryEvent("window.imraidview",b,a)}catch(e){}};a.onUserAudioMuteInteraction=function(a){try{sdkController.onUserAudioMuteInteraction("window.imraidview",a)}catch(b){}};a.enableFallbackViewabilityFunctionality=
function(){b=!0;a.checkFallbackViewable()&&window.mraid.broadcastEvent("viewableChange",!0);mraid.addEventListener("sizeChange",function(){window.mraid.broadcastEvent("viewableChange",a.checkFallbackViewable())})};a.checkFallbackViewable=function(){try{var b=mraidview.getCurrentPosition(),f=b.height;return 40<=b.width&&40<=f?!0:!1}catch(d){a.showAlert("checkFallbackViewable: "+d)}};a.fallbackViewabilityEnabled=function(){return b};a.getSafeArea=function(){try{return JSON.parse(sdkController.getSafeArea("window.imraidview"))}catch(a){return null}}})();
(function(){var a=window.imraid=new InmobiObj,b=window.imraidview;a.getOrientation=b.getOrientation;a.setOrientationProperties=b.setOrientationProperties;a.getOrientationProperties=b.getOrientationProperties;a.saveContentIDMap={};a.saveContent=function(c,d,e){var g=arguments.length,h,k=null;if(3>g){if("function"===typeof arguments[g-1])h=arguments[g-1];else return;k={reason:1}}else a.saveContentIDMap[c]&&(h=arguments[2],k={reason:11,url:arguments[1]});"function"!==!h&&(k?(window.imraid.addEventListener("saveContent_failed_"+
c,h),window.imraid.sendSaveContentResult("saveContent_failed_"+c,"failed",JSON.stringify(k))):(a.removeEventListener("saveContent_"+c),a.saveContentIDMap[c]=!0,b.saveContent(c,d,e)))};a.cancelSaveContent=function(a){b.cancelSaveContent(a)};a.asyncPing=function(c){"string"!=typeof c?a.broadcastEvent("error","URL is required.","asyncPing"):b.asyncPing(c)};a.disableCloseRegion=b.disableCloseRegion;a.getSdkVersion=b.getSdkVersion;a.log=function(c){"undefined"==typeof c?a.broadcastEvent("error","message is required.",
"log"):"string"==typeof c?b.log(c):b.log(JSON.stringify(c))};a.getInMobiAIVersion=function(){return"2.0"};a.getVendorName=function(){return"inmobi"};a.openExternal=function(a,c){console.log("openExternal is deprecated, will be removed in future version");mraidview.detectAndBlockFraud("imraid.openExternal")||b.openExternal(a,c)};a.updateToPassbook=function(c){mraidview.detectAndBlockFraud("imraid.updateToPassbook")||("string"!=typeof c?a.broadcastEvent("error","Request must specify a valid URL","updateToPassbook"):
b.updateToPassbook(c))};a.postToSocial=function(a,c,e,g){mraidview.detectAndBlockFraud("imraid.postToSocial")||b.postToSocial(a,c,e,g)};a.getPlatform=b.getPlatform;a.incentCompleted=b.incentCompleted;a.loadSKStore=b.loadSKStore;a.showSKStore=function(a){mraidview.detectAndBlockFraud("imraid.showSKStore")||b.showSKStore(a)};a.skoverlay=b.skoverlay;a.skoverlayWithSkan=b.skoverlayWithSkan;a.zoom=b.zoom;a.dismissSKOverlay=b.dismissSKOverlay;a.supports=function(a){return b.supports(a)};a.isDeviceMuted=
function(){return!imIsObjValid(a.listeners.deviceMuted)?-1:b.isDeviceMuted()};a.isHeadPhonesPlugged=function(){return!imIsObjValid(a.listeners.headphones)?!1:b.isHeadPhonesPlugged()};a.getDeviceVolume=function(){return b.getDeviceVolume()};a.setDeviceVolume=function(a){b.setDeviceVolume(a)};a.hideStatusBar=function(){b.hideStatusBar()};a.setOpaqueBackground=function(){b.setOpaqueBackground()};a.getRenderableAdIndexes=b.getRenderableAdIndexes;a.getCurrentRenderingIndex=b.getCurrentRenderingIndex;a.showAd=
b.showAd;a.timeSinceShow=b.timeSinceShow;a.closeAll=b.closeAll;a.loadAd=b.loadAd;a.setAdContext=b.setAdContext;a.getAdContext=b.getAdContext;a.getShowTimeStamp=b.getShowTimeStamp;a.disableBackButton=b.disableBackButton;a.isBackButtonDisabled=b.isBackButtonDisabled;a.startDownloader=b.startDownloader;a.getDownloadProgress=b.getDownloadProgress;a.getDownloadStatus=b.getDownloadStatus;a.fireEvent=b.fireEvent;a.saveBlob=b.saveBlob;a.getBlob=b.getBlob;a.setCloseEndCardTracker=b.setCloseEndCardTracker;
a.openWithoutTracker=b.openWithoutTracker;a.impressionRendered=b.impressionRendered;a.onGestureDetected=b.onGestureDetected;a.onUserLandingCompleted=b.onUserLandingCompleted;a.customExpand=b.customExpand;a.closeCustomExpand=b.closeCustomExpand;a.customExpandInNative=b.customExpandInNative;a.impressionFired=b.impressionFired;a.getImraidVersion=b.getImraidVersion;a.getMaxDeviceVolume=b.getMaxDeviceVolume;a.onAudioStateChanged=b.onAudioStateChanged;a.onUserAudioMuteInteraction=b.onUserAudioMuteInteraction;
a.submitAdReport=b.submitAdReport;a.enableFallbackViewabilityFunctionality=b.enableFallbackViewabilityFunctionality;a.logTelemetryEvent=b.logTelemetryEvent;a.getSafeArea=b.getSafeArea;a.onReceviedSKANCallback=b.onReceviedSKANCallback;a.getOpenMode=b.getOpenMode;try{a.addEventListener("onUserLandingCompleted",function(){1080>b.getSdkVersionInt()&&a.broadcastEvent("onUserLandingInitialized")})}catch(c){}})();
(function(){var a=window._im_imaiview={ios:{}};window.imaiview=a;a.broadcastEvent=function(){for(var a=Array(arguments.length),c=0;c<arguments.length;c++)a[c]=arguments[c];c=a.shift();try{window.mraid.broadcastEvent(c,a)}catch(f){}};a.getPlatform=function(){return"android"};a.getPlatformVersion=function(){return sdkController.getPlatformVersion("window.imaiview")};a.log=function(a){sdkController.log("window.imaiview",a)};a.openEmbedded=function(a){sdkController.openEmbedded("window.imaiview",a)};
a.openExternal=function(a,c){600<=getSdkVersionInt()?sdkController.openExternal("window.imaiview",a,c):sdkController.openExternal("window.imaiview",a)};a.ping=function(a,c){sdkController.ping("window.imaiview",a,c)};a.pingInWebView=function(a,c){sdkController.pingInWebView("window.imaiview",a,c)};a.getSdkVersion=function(){try{var a=sdkController.getSdkVersion("window.imaiview");if("string"==typeof a&&null!=a)return a}catch(c){return"3.7.0"}};a.onUserInteraction=function(a){if("object"!=typeof a||
null==a)sdkController.onUserInteraction("window.imaiview",null);else try{sdkController.onUserInteraction("window.imaiview",JSON.stringify(a))}catch(c){sdkController.onUserInteraction("window.imaiview",null)}};a.fireAdReady=function(){sdkController.fireAdReady("window.imaiview")};a.fireAdFailed=function(){sdkController.fireAdFailed("window.imaiview")};a.broadcastEvent=function(){window.imai.broadcastEvent.apply(window.imai,arguments)}})();
(function(){var a=window._im_imaiview;window._im_imai=new InmobiObj;window._im_imai.ios=new InmobiObj;var b=window._im_imai;window.imai=window._im_imai;b.matchString=function(a,b){if("string"!=typeof a||null==a||null==b)return-1;var d=-1;try{d=a.indexOf(b)}catch(e){}return d};b.isHttpUrl=function(a){return"string"!=typeof a||null==a?!1:0==b.matchString(a,"http://")?!0:0==b.matchString(a,"https://")?!0:!1};b.appendTapParams=function(a,f,d){if(!imIsObjValid(f)||!imIsObjValid(d))return a;b.isHttpUrl(a)&&
(a=-1==b.matchString(a,"?")?a+("?u-tap-o="+f+","+d):a+("&u-tap-o="+f+","+d));return a};b.performAdClick=function(a,f){f=f||event;if(imIsObjValid(a)){var d=a.clickConfig,e=a.landingConfig;if(!imIsObjValid(d)&&!imIsObjValid(e))b.log("click/landing config are invalid, Nothing to process ."),this.broadcastEvent("error","click/landing config are invalid, Nothing to process .");else{var g=null,h=null,k=null,m=null,n=null,l=null,q=null,p=null;if(imIsObjValid(f))try{m=f.changedTouches[0].pageX,n=f.changedTouches[0].pageY}catch(r){n=
m=0}imIsObjValid(e)?imIsObjValid(d)?(l=e.url,q=e.fallbackUrl,p=e.urlType,g=d.url,h=d.pingWV,k=d.fr):(l=e.url,p=e.urlType):(l=d.url,p=d.urlType);d=b.getPlatform();try{if("boolean"!=typeof k&&"number"!=typeof k||null==k)k=!0;if(0>k||1<k)k=!0;if("boolean"!=typeof h&&"number"!=typeof h||null==h)h=!0;if(0>h||1<h)h=!0;if("number"!=typeof p||null==p)p=0;g=b.appendTapParams(g,m,n);imIsObjValid(g)?!0==h?b.pingInWebView(g,k):b.ping(g,k):b.log("clickurl provided is null.");if(imIsObjValid(l))switch(imIsObjValid(g)||
(l=b.appendTapParams(l,m,n)),p){case 1:b.openEmbedded(l);break;case 2:"ios"==d?b.ios.openItunesProductView(l):this.broadcastEvent("error","Cannot process openItunesProductView for os"+d);break;default:b.openExternal(l,q)}else b.log("Landing url provided is null.")}catch(s){}}}else b.log(" invalid config, nothing to process ."),this.broadcastEvent("error","invalid config, nothing to process .")};b.performActionClick=function(a,f){f=f||event;if(imIsObjValid(a)){var d=a.clickConfig,e=a.landingConfig;
if(!imIsObjValid(d)&&!imIsObjValid(e))b.log("click/landing config are invalid, Nothing to process ."),this.broadcastEvent("error","click/landing config are invalid, Nothing to process .");else{var g=null,h=null,k=null,m=null,n=null;if(imIsObjValid(f))try{m=f.changedTouches[0].pageX,n=f.changedTouches[0].pageY}catch(l){n=m=0}imIsObjValid(d)&&(g=d.url,h=d.pingWV,k=d.fr);try{if("boolean"!=typeof k&&"number"!=typeof k||null==k)k=!0;if(0>k||1<k)k=!0;if("boolean"!=typeof h&&"number"!=typeof h||null==h)h=
!0;if(0>h||1<h)h=!0;g=b.appendTapParams(g,m,n);imIsObjValid(g)?!0==h?b.pingInWebView(g,k):b.ping(g,k):b.log("clickurl provided is null.");b.onUserInteraction(e)}catch(q){}}}else b.log(" invalid config, nothing to process ."),this.broadcastEvent("error","invalid config, nothing to process .")};b.getVersion=function(){return"1.0"};b.getPlatform=a.getPlatform;b.getPlatformVersion=a.getPlatformVersion;b.log=a.log;b.openEmbedded=function(b){console.log("openEmbedded is deprecated, will be removed in future version");
mraidview.detectAndBlockFraud("imai.openEmbedded")||a.openEmbedded(b)};b.openExternal=function(b,f){console.log("openExternal is deprecated, will be removed in future version");mraidview.detectAndBlockFraud("imai.openExternal")||a.openExternal(b,f)};b.ping=a.ping;b.pingInWebView=a.pingInWebView;b.onUserInteraction=a.onUserInteraction;b.getSdkVersion=a.getSdkVersion;b.loadSKStore=a.loadSKStore;b.showSKStore=function(b){mraidview.detectAndBlockFraud("imai.showSKStore")||a.showSKStore(b)};b.ios.openItunesProductView=
function(b){mraidview.detectAndBlockFraud("imai.ios.openItunesProductView")||a.ios.openItunesProductView(b)};b.fireAdReady=a.fireAdReady;b.fireAdFailed=a.fireAdFailed})();