function (c) {
      var d = a.c.C ? 'limited' : 'full'; var e = T(c.accessMode, ra) ? c.accessMode : null; d = e ? 'full' == e && 'limited' == d ? d : e : d; c.accessMode = d; e = 'full' != d; d = Sb(); var g = c.resourceUrl, l = a.b.document, f = l.createElement('iframe'); e && (f.sandbox = 'allow-scripts'); f.id = 'omid-verification-script-frame-' + d; f.style.display = 'none'; f.srcdoc = "<html><head>\n<script type=\"text/javascript\">window['omidVerificationProperties'] = {\n'serviceWindow': window.parent,\n'injectionId': '" +
        (d + '\',\n};\x3c/script>\n<script type="text/javascript" src="') + g.replace(/"/g, '&quot;') + '">\x3c/script>\n</head><body></body></html>'; l.body.appendChild(f); e = c.vendorKey; g = c.verificationParameters; e = void 0 === e ? '' : e; g = void 0 === g ? '' : g; e && 'string' === typeof e && '' !== e && g && 'string' === typeof g && '' !== g && (a.f.i[e] = g); a.c.v.set(d, c)
    })
  }; function Ub() { var a = Vb, b = Wb, c = this; this.c = X; this.b = a; this.a = G(); this.g = b; this.f = !1; this.registerSessionObserver(function (d) { return Xb(c, d) }) } n = Ub.prototype; n.registerSessionObserver = function (a) { ab(this.c, a) }; n.setSlotElement = function (a) { this.a.h = a; this.b && rb(this.b) }; n.setElementBounds = function (a) { this.a.j = a; this.b && rb(this.b); this.b && sb(this.b) }; n.error = function (a, b) { db(this.c, a, b) }; n.registerAdEvents = function () { ob(this.c, 'javascript') }; n.registerMediaEvents = function () { nb(this.c, 'javascript') };
  function Y(a, b, c) { 'impression' == b ? pb(a.c, 'javascript') && (jb(a.c, 'javascript'), a.b && M(a.b)) : ('loaded' == b ? (c = void 0 === c ? null : c, K(a.c, 'javascript') && kb(a.c, 'javascript', c)) : K(a.c, 'javascript') && lb(a.c, b, 'javascript', c), ['loaded', 'start'].includes(b) && a.b && M(a.b)) } n.injectVerificationScriptResources = function (a) { var b = this.g; b.a.push.apply(b.a, q(a)); if (this.f) try { Tb(this.g) } catch (c) { I(c.message) } };
  n.setCreativeType = function (a, b) { b = void 0 === b ? null : b; if (!this.a.b || this.a.a) this.a.a = a, 'video' == a || 'audio' == a ? this.a.b = 'video' : 'htmlDisplay' == a || 'nativeDisplay' == a ? this.a.b = 'display' : 'definedByJavaScript' == a && b && (this.a.b = 'none' == b ? 'display' : 'video') }; n.setImpressionType = function (a) { if (!this.a.b || this.a.a) this.a.f = a };
  function Xb(a, b) { if ('sessionStart' === b.type) { a.f = !0; try { Tb(a.g) } catch (c) { I(c.message) } } 'sessionFinish' === b.type && (a.f = !1, (b = G().c) && 'native' == b.adSessionType || a.registerSessionObserver(function (c) { return Xb(a, c) })) } n.setClientInfo = function (a, b, c) { var d = this.a.c || {}; d.omidJsInfo = Object.assign({}, d.omidJsInfo, { sessionClientVersion: a, partnerName: b, partnerVersion: c }); this.a.c = d; return this.a.c.omidJsInfo.serviceVersion }; function Yb(a) { return /\d+\.\d+\.\d+(-.*)?/.test(a) } function Zb(a) { a = a.split('-')[0].split('.'); for (var b = ['1', '0', '3'], c = 0; 3 > c; c++) { var d = parseInt(a[c], 10), e = parseInt(b[c], 10); if (d > e) break; else if (d < e) return !1 } return !0 }; function $b(a, b) { return Yb(a) && Zb(a) ? b ? b : [] : b && 'string' === typeof b ? JSON.parse(b) : [] }; function ac() { var a = bc; var b = void 0 === b ? omidGlobal : b; this.a = a; this.f = b; this.b = new V; this.f.omid = this.f.omid || {}; this.f.omid.v1_SessionServiceCommunication = this.b; this.c = b && b.addEventListener && b.postMessage ? new Rb(b) : null; this.g = null; this.b.a = this.h.bind(this); this.c && (this.c.a = this.i.bind(this)) } ac.prototype.h = function (a, b) { cc(this, a, b, this.b) };
  ac.prototype.i = function (a, b) { this.g || (this.g = b); this.g != b ? I('The source window of session client post messages cannot be changed from the source of the first message.') : cc(this, a, b, this.c) };
  function cc(a, b, c, d) { function e(h) { for (var k = [], m = 0; m < arguments.length; ++m)k[m] = arguments[m]; k = new U(g, 'response', f, Yb(f) && Zb(f) ? k : JSON.stringify(k)); d.b(k, c) } var g = b.b, l = b.method, f = b.version; b = $b(f, b.a); try { dc(a, l, e, b) } catch (h) { d.b(new U(g, 'error', f, '\n        name: ' + h.name + '\n        message: ' + h.message + '\n        filename: ' + h.filename + '\n        lineNumber: ' + h.lineNumber + '\n        columnNumber: ' + h.columnNumber + '\n        stack: ' + h.stack + '\n        toString(): ' + h.toString()), c) } }
  function dc(a, b, c, d) {
    switch (b) {
      case 'SessionService.registerAdEvents': a.a.registerAdEvents(); break; case 'SessionService.registerMediaEvents': a.a.registerMediaEvents(); break; case 'SessionService.registerSessionObserver': a.a.registerSessionObserver(c); break; case 'SessionService.setSlotElement': c = p(d).next().value; a.a.setSlotElement(c); break; case 'SessionService.setVideoElement': c = p(d).next().value; a = a.a; a.a.i = c; a.b && rb(a.b); break; case 'SessionService.setElementBounds': c = p(d).next().value; a.a.setElementBounds(c);
        break; case 'SessionService.startSession': I('Session start from JS is not supported in mobile app.'); break; case 'SessionService.finishSession': I('Session finish from JS is not supported in mobile app.'); break; case 'SessionService.impressionOccurred': Y(a.a, 'impression'); break; case 'SessionService.loaded': (c = p(d).next().value) ? (b = { skippable: c.isSkippable, autoPlay: c.isAutoPlay, position: c.position }, c.isSkippable && (b.skipOffset = c.skipOffset), Y(a.a, 'loaded', b)) : Y(a.a, 'loaded'); break; case 'SessionService.start': b =
          p(d); c = b.next().value; b = b.next().value; Y(a.a, 'start', { duration: c, mediaPlayerVolume: b }); break; case 'SessionService.firstQuartile': Y(a.a, 'firstQuartile'); break; case 'SessionService.midpoint': Y(a.a, 'midpoint'); break; case 'SessionService.thirdQuartile': Y(a.a, 'thirdQuartile'); break; case 'SessionService.complete': Y(a.a, 'complete'); break; case 'SessionService.pause': Y(a.a, 'pause'); break; case 'SessionService.resume': Y(a.a, 'resume'); break; case 'SessionService.bufferStart': Y(a.a, 'bufferStart'); break; case 'SessionService.bufferFinish': Y(a.a,
            'bufferFinish'); break; case 'SessionService.skipped': Y(a.a, 'skipped'); break; case 'SessionService.volumeChange': c = { mediaPlayerVolume: p(d).next().value }; Y(a.a, 'volumeChange', c); break; case 'SessionService.playerStateChange': c = { state: p(d).next().value }; Y(a.a, 'playerStateChange', c); break; case 'SessionService.adUserInteraction': c = { interactionType: p(d).next().value }; Y(a.a, 'adUserInteraction', c); break; case 'SessionService.setClientInfo': var e = p(d); b = e.next().value; d = e.next().value; e = e.next().value; a = a.a.setClientInfo(b,
              d, e); c(a); break; case 'SessionService.injectVerificationScriptResources': c = p(d).next().value; a.a.injectVerificationScriptResources(c); break; case 'SessionService.setCreativeType': c = p(d).next().value; a.a.setCreativeType(c); break; case 'SessionService.setImpressionType': c = p(d).next().value; a.a.setImpressionType(c); break; case 'SessionService.setContentUrl': c = p(d).next().value; a.a.a.s = c; break; case 'SessionService.sessionError': b = p(d), c = b.next().value, b = b.next().value, a.a.error(c, b)
    }
  }; function Z() { var a = X, b = ec, c = fc, d = Vb; this.f = bc; this.a = a; this.c = b; this.h = c; this.g = d; this.b = G() } n = Z.prototype;
  n.S = function (a) {
    if (!(!(a && R(a) && T(a.impressionOwner, qa)) || 'videoEventsOwner' in a && null != a.videoEventsOwner && !T(a.videoEventsOwner, qa) || 'mediaEventsOwner' in a && null != a.mediaEventsOwner && !T(a.mediaEventsOwner, qa))) {
      if (a.creativeType && a.impressionType) { var b = a.mediaEventsOwner; null == this.b.a && this.f.setCreativeType(a.creativeType, b); null == this.b.f && (this.b.f = a.impressionType); nb(this.a, b) } else b = a.videoEventsOwner, this.b.b = null == b || 'none' === b ? 'display' : 'video', this.b.a = null, this.b.f = null, nb(this.a, b);
      ob(this.a, a.impressionOwner); a && null != a.isolateVerificationScripts && 'boolean' === typeof a.isolateVerificationScripts && (this.b.C = a.isolateVerificationScripts)
    }
  };
  n.V = function (a, b, c, d) {
    var e; if (R(b)) { if (e = T(b.environment, ta) && T(b.adSessionType, pa)) e = b.omidNativeInfo, e = R(e) ? S(e.partnerName) && S(e.partnerVersion) : !1; e && (e = b.app, e = R(e) ? S(e.libraryVersion) && S(e.appId) : !1) } else e = !1; e && (Mb(d) && (this.b.v = new Map(Object.entries(d))), d = this.f, c = void 0 === c ? null : c, null == a && (a = Sb()), d.a.adSessionId = a, a = d.a, e = a.c || {}, b.omidJsInfo = Object.assign({}, e.omidJsInfo || {}, b.omidJsInfo || {}), e = b = Object.assign({}, e, b), a.C || (null != a.i ? (e.videoElement = a.i, e.accessMode = 'full') : null !=
      a.h && (e.slotElement = a.h, e.accessMode = 'full')), a.c = b, void 0 !== b.contentUrl && (a.s = b.contentUrl), eb(d.c, c), d.b && M(d.b))
  }; n.T = function () { var a = this.f; ib(a.c); a.b.m() }; n.Z = function (a) { R(a) && Lb(a.x) && Lb(a.y) && Lb(a.width) && Lb(a.height) && (this.b.G = a, qb(this.c, 'container')) }; n.$ = function (a) { T(a, sa) && (this.b.m = a, 'backgrounded' === a ? qb(this.c, 'container', 'backgrounded') : qb(this.c, 'container')) }; n.W = function (a) { 'impression' === a && (this.L(), this.g && M(this.g)) }; n.L = function () { pb(this.a, 'native') && jb(this.a, 'native') };
  n.U = function (a) { a = void 0 === a ? null : a; K(this.a, 'native') && kb(this.a, 'native', a) }; n.error = function (a, b) { T(a, na) && db(this.a, a, b) }; n.X = function (a, b) { this.M(a, b) }; n.M = function (a, b) { K(this.a, 'native') && T(a, y) && (void 0 === b || R(b)) && ('loaded' == a ? kb(this.a, 'native', b) : lb(this.a, a, 'native', b)) }; n.Y = function (a) { if ('none' !== this.a.a.g && 'number' === typeof a && !isNaN(a)) { this.b.u = a; a = this.h; var b = a.a.B; null != b && lb(a.b, 'volumeChange', 'native', { mediaPlayerVolume: b, deviceVolume: a.a.u }) } }; Z.prototype.startSession = Z.prototype.V;
  Z.prototype.error = Z.prototype.error; Z.prototype.finishSession = Z.prototype.T; Z.prototype.publishAdEvent = Z.prototype.W; Z.prototype.publishImpressionEvent = Z.prototype.L; Z.prototype.publishVideoEvent = Z.prototype.X; Z.prototype.publishMediaEvent = Z.prototype.M; Z.prototype.publishLoadedEvent = Z.prototype.U; Z.prototype.setNativeViewHierarchy = Z.prototype.Z; Z.prototype.setState = Z.prototype.$; Z.prototype.setDeviceVolume = Z.prototype.Y; Z.prototype.init = Z.prototype.S; function gc() { var a = X, b = hc; var c = void 0 === c ? H : c; this.g = a; this.a = b; this.h = {}; this.f = {}; this.c = new V; c.omid = c.omid || {}; c.omid.v1_VerificationServiceCommunication = this.c; this.b = null; c && c.addEventListener && c.postMessage && (this.b = new Rb(c)); this.c.a = this.i.bind(this); this.b && (this.b.a = this.j.bind(this)) } function ic(a, b, c, d) { Ab(a.a, b, c, d) } function jc(a, b, c, d) { zb(a.a, 'downloadJavaScriptResource')(b, c, d) } gc.prototype.j = function (a, b) { this.b && kc(this, a, b, this.b) }; gc.prototype.i = function (a, b) { kc(this, a, b, this.c) };
  function kc(a, b, c, d) {
    function e(B) { for (var W = [], oa = 0; oa < arguments.length; ++oa)W[oa] = arguments[oa]; W = new U(g, 'response', f, Yb(f) && Zb(f) ? W : JSON.stringify(W)); d.b(W, c) } var g = b.b, l = b.method, f = b.version; b = $b(f, b.a); try {
      switch (l) {
        case 'VerificationService.addEventListener': var h = p(b).next().value; Za(a.g, h, e); break; case 'VerificationService.addSessionListener': var k = p(b), m = k.next().value, z = k.next().value; ab(a.g, e, m, z); break; case 'VerificationService.sendUrl': var xa = p(b).next().value; ic(a, xa, function () { return e(!0) },
          function () { return e(!1) }); break; case 'VerificationService.setTimeout': var P = p(b), Q = P.next().value, F = P.next().value; a.h[Q] = wb(a.a, 'setTimeout')(e, F); break; case 'VerificationService.clearTimeout': var pc = p(b).next().value; yb(a.a, a.h[pc]); break; case 'VerificationService.setInterval': var Jb = p(b), qc = Jb.next().value, rc = Jb.next().value; a.f[qc] = vb(a.a, e, rc); break; case 'VerificationService.clearInterval': var sc = p(b).next().value; xb(a.a, a.f[sc]); break; case 'VerificationService.injectJavaScriptResource': var tc =
            p(b).next().value; jc(a, tc, function (B) { return e(!0, B) }, function () { return e(!1) }); break; case 'VerificationService.getVersion': p(b).next(); var uc = G().c.omidJsInfo; e(uc.serviceVersion)
      }
    } catch (B) {
      d.b(new U(g, 'error', f, '\n              name: ' + B.name + '\n              message: ' + B.message + '\n              filename: ' + B.filename + '\n              lineNumber: ' + B.lineNumber + '\n              columnNumber: ' + B.columnNumber + '\n              stack: ' + B.stack + '\n              toString(): ' + B.toString() + '\n          '),
        c)
    }
  }; function lc() { var a = H.document.createElement('iframe'); a.id = 'omid_v1_present'; a.name = 'omid_v1_present'; a.style.display = 'none'; H.document.body.appendChild(a) } function mc() { var a = new MutationObserver(function (b) { b.forEach(function (c) { 'BODY' === c.addedNodes[0].nodeName && (lc(), a.disconnect()) }) }); a.observe(H.document.documentElement, { childList: !0 }) }; var X = new Ta, hc = new function () { var a; this.a = a = void 0 === a ? omidGlobal : a }; new gc; var nc = new function () { }, oc = new function () { }, ec = new function () { this.b = X; this.c = oc; this.a = G() }, vc; H ? vc = H.IntersectionObserver && (H.MutationObserver || H.ResizeObserver) ? new O(H, nc, ec, X) : new N(H, oc, ec, hc, X) : vc = null; var Vb = vc, Wb = new function () { var a = X; var b = void 0 === b ? H : b; this.f = a; this.b = b; this.c = G(); this.a = [] }, bc = new Ub, fc = new function () { var a = X, b = G(); this.b = a; this.a = b }; H.omidBridge = new Z; new ac;
  if (H.frames && H.document && !('omid_v1_present' in H.frames)) { var wc; if (wc = null == H.document.body) wc = 'MutationObserver' in H; wc ? mc() : H.document.body ? lc() : H.document.write('<iframe style="display:none" id="omid_v1_present" name="omid_v1_present"></iframe>') };
}).call(this, this);

