function fc(a,b){return(a=a.match(new RegExp('^'+b+'(.*)')))&&a[1]};function gc(a,b){this.i=b=void 0===b?J:b;var c=this;a.addEventListener('message',function(d){if('object'===typeof d.data){var e=d.data;ac(e)&&d.source&&c.g&&c.g(bc(e),d.source)}})}v(gc,dc);gc.prototype.h=function(a,b){b=void 0===b?this.i:b;if(!b)throw Error('Message destination must be defined at construction time or when sending the message.');b.postMessage(cc(a),'*')};function hc(a,b){b=void 0===b?{}:b;var c=J.webkit?J.webkit.messageHandlers.omidJsSessionService:J.omidJsSessionService;if(!c)return!1;c.postMessage(JSON.stringify({method:a,data:b}));return!0};function ic(){this.g=jc}n=ic.prototype;n.registerSessionObserver=function(a,b){Xb(V(this.g,a),b)};n.setSlotElement=function(a,b){V(this.g,a).setSlotElement(b)};n.setElementBounds=function(a,b){V(this.g,a).setElementBounds(b)};
function kc(a,b,c,d,e){e=void 0===e?null:e;a=V(a.g,b);var f=a.g.m;f.sessionOwner||(f.sessionOwner=d?'native':'javascript');d?(b=b||Sb(),a.g.adSessionId=b,c.canMeasureVisibility=a.i.I(),Ra(a.g,c),eb(a.h,e),a.i&&zb(a.i)):b?(Ra(a.g,c),hc('startSession',{adSessionId:b})||K('On App, the native-layer JS Session Service must be initialized before starting an ad session using the JS API.')):K('Session client must be updated to start an App session from JS.')}
function lc(a,b,c){c?(b=V(a.g,b),a=a.g,a.g=Zb(a),jb(b.h),b.i.A(),b.o&&(b.o.stop(),b.o=null)):b?hc('finishSession',{adSessionId:b})||K('On App, the native-layer JS Session Service must be initialized before finishing an ad session using the JS API.'):K('Session client must be updated to finish an App session from JS.')}n.error=function(a,b,c){V(this.g,a).error(b,c)};
function Y(a,b,c,d){a=V(a.g,b);'impression'==c?rb(a.h,'javascript')&&(kb(a.h,'javascript'),a.i&&zb(a.i)):('loaded'==c?(d=void 0===d?null:d,pb(a.h,'javascript')&&lb(a.h,'javascript',d)):pb(a.h,'javascript')&&mb(a.h,c,'javascript',d),['loaded','start'].includes(c)&&a.i&&zb(a.i))}n.injectVerificationScriptResources=function(a,b){V(this.g,a).injectVerificationScriptResources(b)};n.setCreativeType=function(a,b,c){c=void 0===c?null:c;V(this.g,a).setCreativeType(b,c)};
n.setImpressionType=function(a,b){V(this.g,a).setImpressionType(b)};n.setClientInfo=function(a,b,c,d){var e=this.g;if(null==a)a=e.g;else{var f=[].concat(q(e.h.values())).includes(e.g)?Zb(e):e.g;e.h.set(a,f);a=f}return a.setClientInfo(b,c,d)};function mc(a){a=a.split('-')[0].split('.');for(var b=['1','0','3'],c=0;3>c;c++){var d=parseInt(a[c],10),e=parseInt(b[c],10);if(d>e)break;else if(d<e)return!1}return!0};function nc(a,b){return/\d+\.\d+\.\d+(-.*)?/.test(a)&&mc(a)?b:JSON.stringify(b)}function oc(a,b){return/\d+\.\d+\.\d+(-.*)?/.test(a)&&mc(a)?b?b:[]:b&&'string'===typeof b?JSON.parse(b):[]};function pc(){var a=qc;var b=void 0===b?omidGlobal:b;this.g=a;this.h=b;this.j=new X;this.h.omid=this.h.omid||{};this.h.omid.v1_SessionServiceCommunication=this.j;this.i=b&&b.addEventListener&&b.postMessage?new gc(b):null;this.j.g=this.m.bind(this);this.i&&(this.i.g=this.l.bind(this))}pc.prototype.m=function(a,b){null!=ec(a.method)&&rc(this,a,b,this.j)};pc.prototype.l=function(a,b){null!=ec(a.method)&&rc(this,a,b,this.i)};
function rc(a,b,c,d){function e(){var k=new W(f,'response',h,nc(h,w.apply(0,arguments)));d.h(k,c)}var f=b.h,g=b.method,h=b.version;b=oc(h,b.g);try{sc(a,g,e,b)}catch(k){d.h(new W(f,'error',h,'\n        name: '+k.name+'\n        message: '+k.message+'\n        filename: '+k.filename+'\n        lineNumber: '+k.lineNumber+'\n        columnNumber: '+k.columnNumber+'\n        stack: '+k.stack+'\n        toString(): '+k.toString()),c)}}
function sc(a,b,c,d){if(null!=ec(b))switch(ec(b)){case 'registerAdEvents':c=p(d).next().value;qb(V(a.g.g,c).h,'javascript');break;case 'registerMediaEvents':c=p(d).next().value;ob(V(a.g.g,c).h,'javascript');break;case 'registerSessionObserver':var e=p(d).next().value;a.g.registerSessionObserver(e,c);break;case 'setSlotElement':e=p(d);c=e.next().value;e=e.next().value;a.g.setSlotElement(e,c);break;case 'setVideoElement':e=p(d);c=e.next().value;e=e.next().value;a=V(a.g.g,e);c&&c.tagName&&'video'===
c.tagName.toLowerCase()?(a.g.j=c,a.i&&Ab(a.i)):K('setVideoElement called with a non-HTMLVideoElement. It will be ignored.');break;case 'setElementBounds':e=p(d);c=e.next().value;e=e.next().value;a.g.setElementBounds(e,c);break;case 'startSession':c=p(d);d=c.next().value;c=c.next().value;b=a.h;if(null!=d&&N(d)){var f=d.customReferenceData;d=d.underEvaluation;P(f)||(f=void 0);'boolean'===typeof d||(d=!1);d={customReferenceData:f,underEvaluation:d};if('object'===typeof Nb(b)){var g=Nb(b),h;'object'===
typeof g&&(h=g.identifier);d.app={appId:h&&'string'===typeof h?h:void 0};b:if(g=Nb(b),'object'===typeof g){try{e=JSON.parse(g.deviceInfo)}catch(m){e=void 0;break b}e={deviceType:e.modelName||'Unknown',osVersion:e.platformVersion||'Unknown',os:'webOS'}}else e=void 0;d.deviceInfo=e;d.deviceCategory='ctv'}else if(Pb(b)){b:{if(Pb(b)){try{var k=Ob(b).application.getCurrentApplication().appInfo.id}catch(m){e=void 0;break b}if('string'===typeof k){e=k;break b}}e=void 0}d.app={appId:e};if(Pb(b)){e=Ob(b).systeminfo;
if('object'===typeof e&&'function'===typeof e.getCapability){g=e.getCapability('http://tizen.org/system/model_name');var l=e.getCapability('http://tizen.org/feature/platform.version')}e={deviceType:g||'Unknown',osVersion:l||'Unknown',os:'tizen'}}else e=void 0;d.deviceInfo=e;Pb(b)&&'object'===typeof Ob(b).tvinputdevice&&(d.deviceCategory='ctv')}}else d=null;if(null==d)break;kc(a.g,c,d,!1);break;case 'finishSession':c=p(d).next().value;lc(a.g,c,!1);break;case 'impressionOccurred':c=p(d).next().value;
Y(a.g,c,'impression');break;case 'loaded':e=p(d);c=e.next().value;e=e.next().value;c?(g={skippable:c.isSkippable,autoPlay:c.isAutoPlay,position:c.position},c.isSkippable&&(g.skipOffset=c.skipOffset),Y(a.g,e,'loaded',g)):Y(a.g,e,'loaded');break;case 'start':g=p(d);c=g.next().value;e=g.next().value;g=g.next().value;Y(a.g,g,'start',{duration:c,mediaPlayerVolume:e});break;case 'firstQuartile':c=p(d).next().value;Y(a.g,c,'firstQuartile');break;case 'midpoint':c=p(d).next().value;Y(a.g,c,'midpoint');break;
case 'thirdQuartile':c=p(d).next().value;Y(a.g,c,'thirdQuartile');break;case 'complete':c=p(d).next().value;Y(a.g,c,'complete');break;case 'pause':c=p(d).next().value;Y(a.g,c,'pause');break;case 'resume':c=p(d).next().value;Y(a.g,c,'resume');break;case 'bufferStart':c=p(d).next().value;Y(a.g,c,'bufferStart');break;case 'bufferFinish':c=p(d).next().value;Y(a.g,c,'bufferFinish');break;case 'skipped':c=p(d).next().value;Y(a.g,c,'skipped');break;case 'volumeChange':e=p(d);c=e.next().value;e=e.next().value;
Y(a.g,e,'volumeChange',{mediaPlayerVolume:c});break;case 'playerStateChange':e=p(d);c=e.next().value;e=e.next().value;Y(a.g,e,'playerStateChange',{state:c});break;case 'adUserInteraction':e=p(d);c=e.next().value;e=e.next().value;Y(a.g,e,'adUserInteraction',{interactionType:c});break;case 'setClientInfo':h=p(d);e=h.next().value;g=h.next().value;l=h.next().value;h=h.next().value;a=a.g.setClientInfo(h,e,g,l);c(a);break;case 'injectVerificationScriptResources':e=p(d);c=e.next().value;e=e.next().value;
a.g.injectVerificationScriptResources(e,c);break;case 'setCreativeType':e=p(d);c=e.next().value;e=e.next().value;a.g.setCreativeType(e,c);break;case 'setImpressionType':e=p(d);c=e.next().value;e=e.next().value;a.g.setImpressionType(e,c);break;case 'setContentUrl':e=p(d);c=e.next().value;e=e.next().value;V(a.g.g,e).g.C=c;break;case 'sessionError':g=p(d),c=g.next().value,e=g.next().value,g=g.next().value,a.g.error(g,c,e)}};function Z(){this.g=qc}n=Z.prototype;
n.da=function(a,b){if(!(!(a&&N(a)&&Q(a.impressionOwner,qa))||'videoEventsOwner'in a&&null!=a.videoEventsOwner&&!Q(a.videoEventsOwner,qa)||'mediaEventsOwner'in a&&null!=a.mediaEventsOwner&&!Q(a.mediaEventsOwner,qa))){b=V(this.g.g,b);if(a.creativeType&&a.impressionType){var c=a.mediaEventsOwner;null==b.g.h&&b.setCreativeType(a.creativeType,c);null==b.g.l&&(b.g.l=a.impressionType);ob(b.h,c)}else c=a.videoEventsOwner,b.g.g=null==c||'none'===c?'display':'video',b.g.h=null,b.g.l=null,ob(b.h,c);qb(b.h,a.impressionOwner);
a&&null!=a.isolateVerificationScripts&&'boolean'===typeof a.isolateVerificationScripts&&(b.g.I=a.isolateVerificationScripts)}};
n.aa=function(a,b,c,d){b&&'string'===typeof b.adSessionType&&(b.adSessionType=b.adSessionType.toLowerCase());var e;if(N(b)){if(e=Q(b.environment,ua)&&Q(b.adSessionType,pa))e=b.omidNativeInfo,e=N(e)?P(e.partnerName)&&P(e.partnerVersion):!1;e&&(e=b.app,e=N(e)?P(e.libraryVersion)&&P(e.appId):!1)}else e=!1;if(e){if($b(d)){e=p(Object.values(d));for(var f=e.next();!f.done;f=e.next())f.value.accessMode='limited';V(this.g.g,a).g.v=new Map(Object.entries(d))}kc(this.g,a,b,!0,c)}else K('Native ad session context invalid; session not started.')};
n.W=function(a){lc(this.g,a,!0)};n.$=function(a,b){N(a)&&O(a.x)&&O(a.y)&&O(a.width)&&O(a.height)&&(b=V(this.g.g,b),b.g.L=a,M(b.j,'container'))};n.ha=function(a,b){Q(a,sa)&&(b=V(this.g.g,b),b.g.A=a,'backgrounded'===a?M(b.j,'container','backgrounded'):M(b.j,'container'))};n.Y=function(a,b){Q(a,ta)&&(b=V(this.g.g,b),b.g.M=a,'locked'===a?M(b.j,'container','deviceLocked'):M(b.j,'container'))};n.ea=function(a){'impression'===a&&this.T()};n.T=function(a){a=V(this.g.g,a);rb(a.h,'native')&&kb(a.h,'native')};
n.X=function(a,b){this.S('loaded',void 0===a?null:a,b)};n.error=function(a,b,c){Q(a,oa)&&this.g.error(c,a,b)};n.fa=function(a,b,c){this.S(a,b,c)};n.S=function(a,b,c){Q(a,y)&&(void 0===b||N(b))&&(c=V(this.g.g,c),pb(c.h,'native')&&('loaded'==a?lb(c.h,'native',b):mb(c.h,a,'native',b)))};n.Z=function(a,b){b=V(this.g.g,b);'none'===b.h.g.o||'number'!==typeof a||isNaN(a)||(b.g.D=a,a=b.s,b=a.g.J,null!=b&&mb(a.h,'volumeChange','native',{mediaPlayerVolume:b,deviceVolume:a.g.D}))};
n.ga=function(a){if(a&&N(a)&&O(a.timestamp)){var b=Na(),c=(b.g||{}).timestamp;if(!c||c<a.timestamp)b.g=a}};Z.prototype.startSession=Z.prototype.aa;Z.prototype.error=Z.prototype.error;Z.prototype.finishSession=Z.prototype.W;Z.prototype.publishAdEvent=Z.prototype.ea;Z.prototype.publishImpressionEvent=Z.prototype.T;Z.prototype.publishVideoEvent=Z.prototype.fa;Z.prototype.publishMediaEvent=Z.prototype.S;Z.prototype.publishLoadedEvent=Z.prototype.X;Z.prototype.setNativeViewHierarchy=Z.prototype.$;
Z.prototype.setState=Z.prototype.ha;Z.prototype.setDeviceLockState=Z.prototype.Y;Z.prototype.setDeviceVolume=Z.prototype.Z;Z.prototype.init=Z.prototype.da;Z.prototype.setLastActivity=Z.prototype.ga;function tc(){var a=jc,b=uc,c=this;var d=void 0===d?J:d;this.j=a;this.g=b;this.l={};this.m={};this.i=new X;d.omid=d.omid||{};d.omid.v1_VerificationServiceCommunication=this.i;this.h=null;d&&d.addEventListener&&d.postMessage&&(this.h=new gc(d));this.i.g=function(e,f){vc(c,e,f,c.i)};this.h&&(this.h.g=function(e,f){c.h&&vc(c,e,f,c.h)})}function wc(a,b,c,d){a=Yb(a.j,d).h;'media'===b||'video'===b?$a(a,c,d):(c={type:b,R:d,G:c},a.j.push(c),Za(a,b,c))}function xc(a,b,c,d){a=Yb(a.j,d);Xb(a,b,c,d)}
function yc(a,b,c,d){xb(a.g,b,c,d)}tc.prototype.setInterval=function(a,b){return this.g.setInterval(a,b)};tc.prototype.clearInterval=function(a){this.g.clearInterval(a)};function zc(a,b,c,d){wb(a.g,'downloadJavaScriptResource')(b,c,d)}
function vc(a,b,c,d){function e(){var B=new W(f,'response',h,nc(h,w.apply(0,arguments)));d.h(B,c)}var f=b.h,g=b.method,h=b.version;b=oc(h,b.g);if(null!=fc(g,'VerificationService.')){g=fc(g,'VerificationService.');try{switch(g){case 'addEventListener':var k=p(b),l=k.next().value,m=k.next().value||Ac(c);wc(a,l,e,m);break;case 'addSessionListener':var t=p(b),I=t.next().value,ba=t.next().value||Ac(c);xc(a,e,I,ba);break;case 'sendUrl':var R=p(b).next().value;yc(a,R,function(){return e(!0)},function(){return e(!1)});
break;case 'setTimeout':var F=p(b),Ec=F.next().value,Fc=F.next().value;a.l[Ec]=ub(a.g,'setTimeout')(e,Fc);break;case 'clearTimeout':var Gc=p(b).next().value;vb(a.g,a.l[Gc]);break;case 'setInterval':var Rb=p(b),Hc=Rb.next().value,Ic=Rb.next().value;a.m[Hc]=a.setInterval(e,Ic);break;case 'clearInterval':var Jc=p(b).next().value;a.clearInterval(a.m[Jc]);break;case 'injectJavaScriptResource':var Kc=p(b).next().value;zc(a,Kc,function(B){return e(!0,B)},function(){return e(!1)});break;case 'getVersion':e('1.5.4-iab4590')}}catch(B){d.h(new W(f,
'error',h,'\n              name: '+B.name+'\n              message: '+B.message+'\n              filename: '+B.filename+'\n              lineNumber: '+B.lineNumber+'\n              columnNumber: '+B.columnNumber+'\n              stack: '+B.stack+'\n              toString(): '+B.toString()+'\n          '),c)}}}
function Ac(a){for(var b=Na().h,c=p(b.keys()),d=c.next();!d.done;d=c.next()){d=d.value;var e=b.get(d);if(e){if(e.contentWindow===a)return d;try{if(e.contentWindow.Object.prototype.isPrototypeOf(a))return d}catch(f){}}}};function Bc(a){var b={};return(b.app='omid_v1_present_app',b.web='omid_v1_present_web',b)[a]}function Cc(a,b){a.document.write('<iframe style="display:none" id="'+(b+'" name="'+b+'" sandbox></iframe>'))}function Dc(a,b){var c=a.document.createElement('iframe');c.id=b;c.name=b;c.style.display='none';c.sandbox='';a.document.body.appendChild(c)}
function Lc(a,b){var c=new MutationObserver(function(d){d.forEach(function(e){'BODY'===e.addedNodes[0].nodeName&&(e=Bc(b),Dc(a,'omid_v1_present'),Dc(a,e),c.disconnect())})});c.observe(a.document.documentElement,{childList:!0})};var uc=new tb,jc=new function(){this.i=uc;this.h=new Map;this.g=Zb(this)},qc=new ic;new tc;J.omidBridge=new Z;new pc;(function(a,b){a.frames&&a.document&&!['omid_v1_present','omid_v1_present_web','omid_v1_present_app'].some(function(c){return!!a.frames[c]})&&(null==a.document.body&&'MutationObserver'in a?Lc(a,b):(b=Bc(b),a.document.body?(Dc(a,'omid_v1_present'),Dc(a,b)):(Cc(a,'omid_v1_present'),Cc(a,b))))})(J,'app');
}).call(this, this);

